from properties import (
    DEVMKT_AGE,
    PALCULT_AGE,
    PARK_AGE,
    POPAREA_AGE,
    TOURZONE_AGE,
    AVG_DEVMKT_AGE,
    AVG_PALCULT_AGE,
    AVG_PARK_AGE,
    AVG_POPAREA_AGE,
    AVG_TOURZONE_AGE,
)
from properties import (
    DEVMKT_GENDER,
    PALCULT_GENDER,
    PARK_GENDER,
    POPAREA_GENDER,
    TOURZONE_GENDER,
    AVG_DEVMKT_GEN,
    AVG_PALCULT_GEN,
    AVG_PARK_GEN,
    AVG_POPAREA_GEN,
    AVG_TOURZONE_GEN,
)
from properties import (
    DEVMKT_NOF_AGE,
    PALCULT_NOF_AGE,
    PARK_NOF_AGE,
    POPAREA_NOF_AGE,
    TOURZONE_NOF_AGE,
    AVG_DEVMKT_NOF_AGE,
    AVG_PALCULT_NOF_AGE,
    AVG_PARK_NOF_AGE,
    AVG_POPAREA_NOF_AGE,
    AVG_TOURZONE_NOF_AGE,
)
from properties import (
    DEVMKT_NOF_GENDER,
    PALCULT_NOF_GENDER,
    PARK_NOF_GENDER,
    POPAREA_NOF_GENDER,
    TOURZONE_NOF_GENDER,
    AVG_DEVMKT_NOF_GEN,
    AVG_PALCULT_NOF_GEN,
    AVG_PARK_NOF_GEN,
    AVG_POPAREA_NOF_GEN,
    AVG_TOURZONE_NOF_GEN,
)




n_age_topic_list = [
    DEVMKT_NOF_AGE,
    PALCULT_NOF_AGE,
    PARK_NOF_AGE,
    POPAREA_NOF_AGE,
    TOURZONE_NOF_AGE,
]
n_gender_topic_list = [
    DEVMKT_NOF_GENDER,
    PALCULT_NOF_GENDER,
    PARK_NOF_GENDER,
    POPAREA_NOF_GENDER,
    TOURZONE_NOF_GENDER,
]


age_retrive_topic_list = [
    AVG_DEVMKT_NOF_AGE,
    AVG_PALCULT_NOF_AGE,
    AVG_PARK_NOF_AGE,
    AVG_POPAREA_NOF_AGE,
    AVG_TOURZONE_NOF_AGE,
]
gender_retrive_topic_list = [
    AVG_DEVMKT_NOF_GEN,
    AVG_PALCULT_NOF_GEN,
    AVG_PARK_NOF_GEN,
    AVG_POPAREA_NOF_GEN,
    AVG_TOURZONE_NOF_GEN,
]


